version: "3.7"
services:
  mongodb:
    image: mongo:4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
    ports:
      - 27017:27017
    container_name: mongo
